-- Inventory ledger and combos foundation.
-- No real data, emails, UUIDs, passwords, or service-role secrets are stored here.

do $$
begin
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'stock_movement_type') then
    create type public.stock_movement_type as enum (
      'opening_balance',
      'purchase',
      'sale',
      'return_in',
      'return_out',
      'write_off',
      'adjustment_in',
      'adjustment_out',
      'combo_reservation',
      'combo_release',
      'order_reservation',
      'order_release',
      'transfer_in',
      'transfer_out'
    );
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'stock_document_status') then
    create type public.stock_document_status as enum ('draft', 'posted', 'cancelled');
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'combo_status') then
    create type public.combo_status as enum ('active', 'inactive', 'archived');
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'combo_component_type') then
    create type public.combo_component_type as enum ('product', 'service');
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'combo_selection_mode') then
    create type public.combo_selection_mode as enum ('fixed', 'choice');
  end if;
end
$$;

alter table public.products
  add column if not exists average_purchase_cost numeric(14,4) not null default 0;

create table if not exists public.stock_documents (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  document_number bigint generated by default as identity,
  type public.stock_movement_type not null,
  status public.stock_document_status not null default 'draft',
  document_date timestamptz not null default now(),
  supplier_name text,
  reference text,
  comment text,
  total_amount numeric(14,2),
  created_by uuid not null references auth.users(id),
  posted_by uuid references auth.users(id),
  posted_at timestamptz,
  cancelled_by uuid references auth.users(id),
  cancelled_at timestamptz,
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stock_documents_total_amount_check check (total_amount is null or total_amount >= 0)
);

create index if not exists stock_documents_organization_id_idx on public.stock_documents (organization_id);
create index if not exists stock_documents_organization_status_idx on public.stock_documents (organization_id, status);
create index if not exists stock_documents_organization_type_idx on public.stock_documents (organization_id, type);
create index if not exists stock_documents_organization_date_idx on public.stock_documents (organization_id, document_date desc);
create index if not exists stock_documents_created_by_idx on public.stock_documents (created_by);

create table if not exists public.stock_document_items (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  document_id uuid not null references public.stock_documents(id) on delete cascade,
  product_id uuid not null references public.products(id),
  quantity numeric(14,3) not null,
  unit_cost numeric(14,4),
  line_total numeric(14,2),
  comment text,
  created_at timestamptz not null default now(),
  constraint stock_document_items_quantity_check check (quantity > 0),
  constraint stock_document_items_unit_cost_check check (unit_cost is null or unit_cost >= 0),
  constraint stock_document_items_line_total_check check (line_total is null or line_total >= 0)
);

create index if not exists stock_document_items_document_id_idx on public.stock_document_items (document_id);
create index if not exists stock_document_items_organization_id_idx on public.stock_document_items (organization_id);
create index if not exists stock_document_items_product_id_idx on public.stock_document_items (product_id);

create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  product_id uuid not null references public.products(id),
  document_id uuid references public.stock_documents(id),
  document_item_id uuid references public.stock_document_items(id),
  movement_type public.stock_movement_type not null,
  quantity_delta numeric(14,3) not null,
  unit_cost numeric(14,4),
  total_cost numeric(14,2),
  reference_type text,
  reference_id uuid,
  comment text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  constraint stock_movements_quantity_delta_check check (quantity_delta <> 0)
);

create index if not exists stock_movements_organization_id_idx on public.stock_movements (organization_id);
create index if not exists stock_movements_product_id_idx on public.stock_movements (product_id);
create index if not exists stock_movements_organization_product_idx on public.stock_movements (organization_id, product_id);
create index if not exists stock_movements_organization_created_idx on public.stock_movements (organization_id, created_at desc);
create index if not exists stock_movements_document_id_idx on public.stock_movements (document_id);
create index if not exists stock_movements_reference_id_idx on public.stock_movements (reference_id);

create table if not exists public.combos (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  category_id uuid references public.catalog_categories(id) on delete set null,
  name text not null,
  description text,
  image_path text,
  sale_price numeric(12,2) not null,
  selection_mode public.combo_selection_mode not null default 'fixed',
  sort_order integer not null default 0,
  status public.combo_status not null default 'active',
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint combos_name_not_blank_check check (length(btrim(name)) > 0),
  constraint combos_sale_price_check check (sale_price >= 0),
  constraint combos_sort_order_check check (sort_order >= 0)
);

create index if not exists combos_organization_id_idx on public.combos (organization_id);
create index if not exists combos_organization_status_idx on public.combos (organization_id, status);
create index if not exists combos_organization_sort_idx on public.combos (organization_id, sort_order);
create index if not exists combos_category_id_idx on public.combos (category_id);

create table if not exists public.combo_components (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  combo_id uuid not null references public.combos(id) on delete cascade,
  component_type public.combo_component_type not null,
  product_id uuid references public.products(id),
  service_id uuid references public.services(id),
  quantity numeric(14,3) not null default 1,
  included_minutes integer,
  sort_order integer not null default 0,
  is_required boolean not null default true,
  created_at timestamptz not null default now(),
  constraint combo_components_quantity_check check (quantity > 0),
  constraint combo_components_sort_order_check check (sort_order >= 0),
  constraint combo_components_product_shape_check check (
    (component_type = 'product' and product_id is not null and service_id is null and included_minutes is null)
    or (component_type = 'service' and service_id is not null and product_id is null)
  ),
  constraint combo_components_included_minutes_check check (included_minutes is null or included_minutes > 0)
);

create index if not exists combo_components_organization_id_idx on public.combo_components (organization_id);
create index if not exists combo_components_combo_id_idx on public.combo_components (combo_id);
create index if not exists combo_components_product_id_idx on public.combo_components (product_id);
create index if not exists combo_components_service_id_idx on public.combo_components (service_id);

create or replace function public.inventory_quantity_sign(document_type public.stock_movement_type)
returns integer
language sql
immutable
as $$
  select case
    when document_type in ('opening_balance', 'purchase', 'return_in', 'adjustment_in', 'transfer_in') then 1
    when document_type in ('sale', 'return_out', 'write_off', 'adjustment_out', 'transfer_out') then -1
    else 0
  end;
$$;

create or replace function public.calculate_product_stock(target_product_id uuid)
returns numeric
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(sum(sm.quantity_delta), 0)::numeric
  from public.stock_movements sm
  where sm.product_id = target_product_id;
$$;

create or replace function public.reconcile_product_stock(target_product_id uuid)
returns public.products
language plpgsql
security definer
set search_path = public
as $$
declare
  product_row public.products;
  calculated_quantity numeric(14,3);
  calculated_average numeric(14,4);
begin
  select * into product_row from public.products where id = target_product_id;
  if product_row.id is null then
    raise exception 'Product was not found.';
  end if;

  if current_setting('app.inventory_write', true) <> '1'
    and not (public.is_platform_owner() or public.is_organization_admin(product_row.organization_id))
  then
    raise exception 'Only organization admins can reconcile stock.';
  end if;

  select coalesce(sum(quantity_delta), 0)::numeric(14,3)
  into calculated_quantity
  from public.stock_movements
  where product_id = target_product_id;

  select coalesce(
    sum(case when quantity_delta > 0 and unit_cost is not null then quantity_delta * unit_cost else 0 end)
    / nullif(sum(case when quantity_delta > 0 and unit_cost is not null then quantity_delta else 0 end), 0),
    0
  )::numeric(14,4)
  into calculated_average
  from public.stock_movements
  where product_id = target_product_id;

  perform set_config('app.inventory_write', '1', true);

  update public.products
  set
    stock_quantity = calculated_quantity,
    average_purchase_cost = calculated_average,
    updated_at = now()
  where id = target_product_id
  returning * into product_row;

  return product_row;
end;
$$;

create or replace view public.product_stock_balances
with (security_barrier = true)
as
select
  p.organization_id,
  p.id as product_id,
  public.calculate_product_stock(p.id)::numeric(14,3) as calculated_quantity,
  p.stock_quantity as cached_quantity,
  (public.calculate_product_stock(p.id) - p.stock_quantity)::numeric(14,3) as variance
from public.products p
where public.is_platform_owner() or public.is_organization_admin(p.organization_id);

create or replace function public.assert_stock_document_scope()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' then
    if new.organization_id is distinct from old.organization_id
      or new.created_by is distinct from old.created_by
      or (old.status = 'posted' and new.status = 'draft')
    then
      raise exception 'Cannot update protected stock document fields.';
    end if;
  end if;

  if not exists (select 1 from public.organizations o where o.id = new.organization_id and o.status = 'active') then
    raise exception 'Organization is not active.';
  end if;

  if current_setting('app.inventory_write', true) = '1' then
    return new;
  end if;

  if not (public.is_platform_owner() or public.is_organization_admin(new.organization_id)) then
    raise exception 'Only organization admins can write stock documents.';
  end if;

  return new;
end;
$$;

create or replace function public.assert_stock_item_scope()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  document_status public.stock_document_status;
begin
  select status into document_status
  from public.stock_documents
  where id = new.document_id and organization_id = new.organization_id;

  if document_status is null then
    raise exception 'Stock document does not belong to this organization.';
  end if;

  if not exists (select 1 from public.products p where p.id = new.product_id and p.organization_id = new.organization_id and p.track_stock = true) then
    raise exception 'Product does not belong to this organization or is not stock-tracked.';
  end if;

  if current_setting('app.inventory_write', true) = '1' then
    return new;
  end if;

  if document_status <> 'draft' then
    raise exception 'Posted or cancelled document items cannot be edited.';
  end if;

  if exists (select 1 from public.products p where p.id = new.product_id and p.status = 'archived') then
    raise exception 'Archived products cannot be used in stock documents.';
  end if;

  if not (public.is_platform_owner() or public.is_organization_admin(new.organization_id)) then
    raise exception 'Only organization admins can write stock items.';
  end if;

  return new;
end;
$$;

create or replace function public.prevent_stock_movement_changes()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if tg_op in ('UPDATE', 'DELETE') then
    raise exception 'Stock movements are immutable.';
  end if;

  if current_setting('app.inventory_write', true) <> '1' then
    raise exception 'Stock movements can be created only by inventory functions.';
  end if;

  return new;
end;
$$;

create or replace function public.prevent_direct_stock_cache_update()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if current_setting('app.inventory_write', true) = '1' then
    return new;
  end if;

  if new.stock_quantity is distinct from old.stock_quantity
    or new.average_purchase_cost is distinct from old.average_purchase_cost
  then
    raise exception 'Stock cache can be updated only by inventory functions.';
  end if;

  return new;
end;
$$;

create or replace function public.prevent_catalog_restricted_write()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' then
    if new.organization_id is distinct from old.organization_id
      or new.created_by is distinct from old.created_by
    then
      raise exception 'Cannot update protected catalog fields.';
    end if;
  end if;

  if not exists (
    select 1
    from public.organizations o
    where o.id = new.organization_id
      and o.status = 'active'
  ) then
    raise exception 'Organization is not active.';
  end if;

  if tg_table_name = 'products'
    and tg_op = 'UPDATE'
    and current_setting('app.inventory_write', true) = '1'
  then
    return new;
  end if;

  if not (
    public.is_platform_owner()
    or public.is_organization_admin(new.organization_id)
  ) then
    raise exception 'Only organization admins can write catalog data for this organization.';
  end if;

  return new;
end;
$$;

create or replace function public.assert_combo_scope()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' then
    if new.organization_id is distinct from old.organization_id
      or new.created_by is distinct from old.created_by
    then
      raise exception 'Cannot update protected combo fields.';
    end if;
  end if;

  if new.category_id is not null and not exists (
    select 1
    from public.catalog_categories c
    where c.id = new.category_id
      and c.organization_id = new.organization_id
      and c.type = 'product'
      and c.status <> 'archived'
  ) then
    raise exception 'Combo category must be an active product category in the same organization.';
  end if;

  if not (public.is_platform_owner() or public.is_organization_admin(new.organization_id)) then
    raise exception 'Only organization admins can write combos.';
  end if;

  if not exists (select 1 from public.organizations o where o.id = new.organization_id and o.status = 'active') then
    raise exception 'Organization is not active.';
  end if;

  return new;
end;
$$;

create or replace function public.assert_combo_component_scope()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if not exists (select 1 from public.combos c where c.id = new.combo_id and c.organization_id = new.organization_id) then
    raise exception 'Combo does not belong to this organization.';
  end if;

  if new.component_type = 'product' and not exists (
    select 1 from public.products p
    where p.id = new.product_id
      and p.organization_id = new.organization_id
      and p.status <> 'archived'
  ) then
    raise exception 'Product component does not belong to this organization or is archived.';
  end if;

  if new.component_type = 'service' and not exists (
    select 1 from public.services s
    where s.id = new.service_id
      and s.organization_id = new.organization_id
      and s.status <> 'archived'
  ) then
    raise exception 'Service component does not belong to this organization or is archived.';
  end if;

  if new.component_type = 'service'
    and new.included_minutes is not null
    and not exists (
      select 1 from public.services s
      where s.id = new.service_id
        and s.pricing_type = 'hourly'
    )
  then
    raise exception 'Included minutes are allowed only for hourly services.';
  end if;

  if not (public.is_platform_owner() or public.is_organization_admin(new.organization_id)) then
    raise exception 'Only organization admins can write combo components.';
  end if;

  return new;
end;
$$;

create or replace function public.set_combo_archived_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.status = 'archived' and old.status is distinct from 'archived' then
    new.archived_at = now();
  elsif new.status <> 'archived' then
    new.archived_at = null;
  end if;

  return new;
end;
$$;

drop trigger if exists stock_documents_set_updated_at on public.stock_documents;
create trigger stock_documents_set_updated_at before update on public.stock_documents
for each row execute function public.set_updated_at();
drop trigger if exists combos_set_updated_at on public.combos;
create trigger combos_set_updated_at before update on public.combos
for each row execute function public.set_updated_at();
drop trigger if exists combos_archived_at on public.combos;
create trigger combos_archived_at before update on public.combos
for each row execute function public.set_combo_archived_at();

drop trigger if exists stock_documents_scope on public.stock_documents;
create trigger stock_documents_scope before insert or update on public.stock_documents
for each row execute function public.assert_stock_document_scope();
drop trigger if exists stock_items_scope on public.stock_document_items;
create trigger stock_items_scope before insert or update on public.stock_document_items
for each row execute function public.assert_stock_item_scope();
drop trigger if exists stock_movements_immutable on public.stock_movements;
create trigger stock_movements_immutable before insert or update or delete on public.stock_movements
for each row execute function public.prevent_stock_movement_changes();
drop trigger if exists products_stock_cache_guard on public.products;
create trigger products_stock_cache_guard before update on public.products
for each row execute function public.prevent_direct_stock_cache_update();
drop trigger if exists combos_scope on public.combos;
create trigger combos_scope before insert or update on public.combos
for each row execute function public.assert_combo_scope();
drop trigger if exists combo_components_scope on public.combo_components;
create trigger combo_components_scope before insert or update on public.combo_components
for each row execute function public.assert_combo_component_scope();

create or replace function public.post_stock_document(target_document_id uuid)
returns public.stock_documents
language plpgsql
security definer
set search_path = public
as $$
declare
  document_row public.stock_documents;
  item_row public.stock_document_items;
  sign integer;
  next_quantity numeric(14,3);
begin
  select * into document_row from public.stock_documents where id = target_document_id;
  if document_row.id is null then raise exception 'Stock document was not found.'; end if;
  if document_row.status <> 'draft' then raise exception 'Only draft documents can be posted.'; end if;
  if not (public.is_platform_owner() or public.is_organization_admin(document_row.organization_id)) then
    raise exception 'Only organization admins can post stock documents.';
  end if;
  if not exists (select 1 from public.organizations o where o.id = document_row.organization_id and o.status = 'active') then
    raise exception 'Organization is not active.';
  end if;

  sign := public.inventory_quantity_sign(document_row.type);
  if sign = 0 then raise exception 'This stock document type is not postable at this stage.'; end if;

  if not exists (select 1 from public.stock_document_items where document_id = target_document_id) then
    raise exception 'Document must contain at least one item.';
  end if;

  perform set_config('app.inventory_write', '1', true);

  for item_row in
    select * from public.stock_document_items where document_id = target_document_id order by created_at asc
  loop
    if not exists (select 1 from public.products p where p.id = item_row.product_id and p.organization_id = document_row.organization_id and p.track_stock = true) then
      raise exception 'Document item product does not belong to this organization.';
    end if;

    next_quantity := public.calculate_product_stock(item_row.product_id) + (item_row.quantity * sign);
    if next_quantity < 0 then
      raise exception 'Stock cannot become negative.';
    end if;

    insert into public.stock_movements (
      organization_id,
      product_id,
      document_id,
      document_item_id,
      movement_type,
      quantity_delta,
      unit_cost,
      total_cost,
      reference_type,
      reference_id,
      comment,
      created_by
    )
    values (
      document_row.organization_id,
      item_row.product_id,
      document_row.id,
      item_row.id,
      document_row.type,
      item_row.quantity * sign,
      item_row.unit_cost,
      coalesce(item_row.line_total, item_row.quantity * coalesce(item_row.unit_cost, 0)),
      'stock_document',
      document_row.id,
      item_row.comment,
      auth.uid()
    );

    perform public.reconcile_product_stock(item_row.product_id);
  end loop;

  update public.stock_documents
  set status = 'posted', posted_by = auth.uid(), posted_at = now(), updated_at = now()
  where id = target_document_id
  returning * into document_row;

  return document_row;
end;
$$;

create or replace function public.cancel_stock_document(target_document_id uuid, target_reason text)
returns public.stock_documents
language plpgsql
security definer
set search_path = public
as $$
declare
  document_row public.stock_documents;
  movement_row public.stock_movements;
  next_quantity numeric(14,3);
begin
  if length(btrim(coalesce(target_reason, ''))) = 0 then
    raise exception 'Cancellation reason is required.';
  end if;

  select * into document_row from public.stock_documents where id = target_document_id;
  if document_row.id is null then raise exception 'Stock document was not found.'; end if;
  if document_row.status = 'cancelled' then raise exception 'Document is already cancelled.'; end if;
  if not (public.is_platform_owner() or public.is_organization_admin(document_row.organization_id)) then
    raise exception 'Only organization admins can cancel stock documents.';
  end if;

  perform set_config('app.inventory_write', '1', true);

  if document_row.status = 'posted' then
    for movement_row in
      select * from public.stock_movements where document_id = target_document_id order by created_at asc
    loop
      next_quantity := public.calculate_product_stock(movement_row.product_id) - movement_row.quantity_delta;
      if next_quantity < 0 then
        raise exception 'Cancellation would make stock negative.';
      end if;

      insert into public.stock_movements (
        organization_id,
        product_id,
        document_id,
        document_item_id,
        movement_type,
        quantity_delta,
        unit_cost,
        total_cost,
        reference_type,
        reference_id,
        comment,
        created_by
      )
      values (
        movement_row.organization_id,
        movement_row.product_id,
        document_row.id,
        movement_row.document_item_id,
        movement_row.movement_type,
        -movement_row.quantity_delta,
        movement_row.unit_cost,
        -coalesce(movement_row.total_cost, 0),
        'stock_document_cancellation',
        document_row.id,
        target_reason,
        auth.uid()
      );

      perform public.reconcile_product_stock(movement_row.product_id);
    end loop;
  end if;

  update public.stock_documents
  set
    status = 'cancelled',
    cancelled_by = auth.uid(),
    cancelled_at = now(),
    cancellation_reason = target_reason,
    updated_at = now()
  where id = target_document_id
  returning * into document_row;

  return document_row;
end;
$$;

create or replace function public.create_opening_stock_document(
  target_product_id uuid,
  target_quantity numeric,
  target_unit_cost numeric default null,
  target_comment text default null
)
returns public.stock_documents
language plpgsql
security definer
set search_path = public
as $$
declare
  product_row public.products;
  document_row public.stock_documents;
begin
  if target_quantity <= 0 then raise exception 'Opening quantity must be greater than zero.'; end if;
  if target_unit_cost is not null and target_unit_cost < 0 then raise exception 'Unit cost cannot be negative.'; end if;

  select * into product_row from public.products where id = target_product_id;
  if product_row.id is null then raise exception 'Product was not found.'; end if;
  if not (public.is_platform_owner() or public.is_organization_admin(product_row.organization_id)) then
    raise exception 'Only organization admins can create opening stock.';
  end if;

  insert into public.stock_documents (organization_id, type, document_date, comment, total_amount, created_by)
  values (
    product_row.organization_id,
    'opening_balance',
    now(),
    target_comment,
    target_quantity * coalesce(target_unit_cost, product_row.purchase_price, 0),
    auth.uid()
  )
  returning * into document_row;

  insert into public.stock_document_items (organization_id, document_id, product_id, quantity, unit_cost, line_total, comment)
  values (
    product_row.organization_id,
    document_row.id,
    product_row.id,
    target_quantity,
    coalesce(target_unit_cost, product_row.purchase_price),
    target_quantity * coalesce(target_unit_cost, product_row.purchase_price, 0),
    target_comment
  );

  return public.post_stock_document(document_row.id);
end;
$$;

create or replace function public.set_combo_status(target_id uuid, target_status public.combo_status)
returns public.combos
language plpgsql
security definer
set search_path = public
as $$
declare
  combo_row public.combos;
begin
  select * into combo_row from public.combos where id = target_id;
  if combo_row.id is null then raise exception 'Combo was not found.'; end if;
  if not (public.is_platform_owner() or public.is_organization_admin(combo_row.organization_id)) then
    raise exception 'Only organization admins can change combo status.';
  end if;
  update public.combos set status = target_status where id = target_id returning * into combo_row;
  return combo_row;
end;
$$;

create or replace view public.combo_availability
with (security_barrier = true)
as
with product_requirements as (
  select
    c.id as combo_id,
    c.organization_id,
    cc.product_id,
    sum(cc.quantity) as required_quantity
  from public.combos c
  join public.combo_components cc on cc.combo_id = c.id
  where cc.component_type = 'product'
    and cc.is_required = true
  group by c.id, c.organization_id, cc.product_id
),
component_availability as (
  select
    pr.combo_id,
    pr.organization_id,
    pr.product_id,
    pr.required_quantity,
    p.track_stock,
    p.status as product_status,
    public.calculate_product_stock(pr.product_id) as current_stock,
    case
      when p.track_stock = false then null
      else floor(public.calculate_product_stock(pr.product_id) / pr.required_quantity)
    end as available_quantity
  from product_requirements pr
  join public.products p on p.id = pr.product_id
)
select
  c.id as combo_id,
  c.organization_id,
  (
    c.status = 'active'
    and public.is_organization_member(c.organization_id)
    and not exists (
      select 1
      from component_availability ca
      where ca.combo_id = c.id
        and ca.track_stock = true
        and (ca.product_status <> 'active' or ca.current_stock < ca.required_quantity)
    )
  ) as is_available,
  case
    when not exists (select 1 from component_availability ca where ca.combo_id = c.id and ca.track_stock = true) then null
    else (
      select min(ca.available_quantity)::integer
      from component_availability ca
      where ca.combo_id = c.id
        and ca.track_stock = true
    )
  end as available_quantity,
  coalesce((
    select jsonb_agg(jsonb_build_object(
      'product_id', ca.product_id,
      'required_quantity', ca.required_quantity,
      'current_stock', ca.current_stock
    ))
    from component_availability ca
    where ca.combo_id = c.id
      and ca.track_stock = true
      and (ca.product_status <> 'active' or ca.current_stock < ca.required_quantity)
  ), '[]'::jsonb) as missing_components
from public.combos c
where public.is_platform_owner() or public.is_organization_member(c.organization_id);

create or replace view public.employee_combos
with (security_barrier = true)
as
select
  c.id,
  c.organization_id,
  c.category_id,
  c.name,
  c.description,
  c.image_path,
  c.sale_price,
  ca.available_quantity,
  coalesce((
    select jsonb_agg(jsonb_build_object(
      'type', cc.component_type,
      'name', coalesce(p.name, s.name),
      'quantity', cc.quantity,
      'included_minutes', cc.included_minutes
    ) order by cc.sort_order)
    from public.combo_components cc
    left join public.products p on p.id = cc.product_id
    left join public.services s on s.id = cc.service_id
    where cc.combo_id = c.id
  ), '[]'::jsonb) as component_preview
from public.combos c
join public.combo_availability ca on ca.combo_id = c.id
where c.status = 'active'
  and ca.is_available = true
  and public.is_organization_member(c.organization_id);

do $$
declare
  product_row public.products;
  document_row public.stock_documents;
begin
  perform set_config('app.inventory_write', '1', true);

  for product_row in
    select *
    from public.products p
    where p.track_stock = true
      and p.stock_quantity > 0
      and not exists (
        select 1
        from public.stock_movements sm
        where sm.product_id = p.id
          and sm.movement_type = 'opening_balance'
          and sm.reference_type = 'migration_202607230005'
      )
  loop
    insert into public.stock_documents (
      organization_id,
      type,
      status,
      document_date,
      comment,
      total_amount,
      created_by,
      posted_by,
      posted_at
    )
    values (
      product_row.organization_id,
      'opening_balance',
      'posted',
      now(),
      'Migrated opening balance from products.stock_quantity',
      product_row.stock_quantity * coalesce(product_row.purchase_price, 0),
      product_row.created_by,
      product_row.created_by,
      now()
    )
    returning * into document_row;

    insert into public.stock_document_items (
      organization_id,
      document_id,
      product_id,
      quantity,
      unit_cost,
      line_total,
      comment
    )
    values (
      product_row.organization_id,
      document_row.id,
      product_row.id,
      product_row.stock_quantity,
      product_row.purchase_price,
      product_row.stock_quantity * coalesce(product_row.purchase_price, 0),
      'Migrated opening balance'
    );

    insert into public.stock_movements (
      organization_id,
      product_id,
      document_id,
      document_item_id,
      movement_type,
      quantity_delta,
      unit_cost,
      total_cost,
      reference_type,
      reference_id,
      comment,
      created_by
    )
    select
      product_row.organization_id,
      product_row.id,
      document_row.id,
      sdi.id,
      'opening_balance',
      product_row.stock_quantity,
      product_row.purchase_price,
      product_row.stock_quantity * coalesce(product_row.purchase_price, 0),
      'migration_202607230005',
      product_row.id,
      'Migrated opening balance',
      product_row.created_by
    from public.stock_document_items sdi
    where sdi.document_id = document_row.id
      and sdi.product_id = product_row.id;

    perform public.reconcile_product_stock(product_row.id);
  end loop;
end
$$;

alter table public.stock_documents enable row level security;
alter table public.stock_document_items enable row level security;
alter table public.stock_movements enable row level security;
alter table public.combos enable row level security;
alter table public.combo_components enable row level security;

drop policy if exists "Stock documents readable by organization admins" on public.stock_documents;
create policy "Stock documents readable by organization admins"
on public.stock_documents for select to authenticated
using (public.is_platform_owner() or public.is_organization_admin(organization_id));
drop policy if exists "Stock documents insertable by organization admins" on public.stock_documents;
create policy "Stock documents insertable by organization admins"
on public.stock_documents for insert to authenticated
with check (public.is_platform_owner() or public.is_organization_admin(organization_id));
drop policy if exists "Stock documents updatable by organization admins" on public.stock_documents;
create policy "Stock documents updatable by organization admins"
on public.stock_documents for update to authenticated
using (public.is_platform_owner() or public.is_organization_admin(organization_id))
with check (public.is_platform_owner() or public.is_organization_admin(organization_id));

drop policy if exists "Stock items readable by organization admins" on public.stock_document_items;
create policy "Stock items readable by organization admins"
on public.stock_document_items for select to authenticated
using (public.is_platform_owner() or public.is_organization_admin(organization_id));
drop policy if exists "Stock items insertable by organization admins" on public.stock_document_items;
create policy "Stock items insertable by organization admins"
on public.stock_document_items for insert to authenticated
with check (public.is_platform_owner() or public.is_organization_admin(organization_id));
drop policy if exists "Stock items updatable by organization admins" on public.stock_document_items;
create policy "Stock items updatable by organization admins"
on public.stock_document_items for update to authenticated
using (public.is_platform_owner() or public.is_organization_admin(organization_id))
with check (public.is_platform_owner() or public.is_organization_admin(organization_id));

drop policy if exists "Stock movements readable by organization admins" on public.stock_movements;
create policy "Stock movements readable by organization admins"
on public.stock_movements for select to authenticated
using (public.is_platform_owner() or public.is_organization_admin(organization_id));

drop policy if exists "Combos readable by organization access" on public.combos;
create policy "Combos readable by organization access"
on public.combos for select to authenticated
using (public.is_platform_owner() or public.is_organization_admin(organization_id));
drop policy if exists "Combos insertable by organization admins" on public.combos;
create policy "Combos insertable by organization admins"
on public.combos for insert to authenticated
with check (public.is_platform_owner() or public.is_organization_admin(organization_id));
drop policy if exists "Combos updatable by organization admins" on public.combos;
create policy "Combos updatable by organization admins"
on public.combos for update to authenticated
using (public.is_platform_owner() or public.is_organization_admin(organization_id))
with check (public.is_platform_owner() or public.is_organization_admin(organization_id));

drop policy if exists "Combo components readable by organization admins" on public.combo_components;
create policy "Combo components readable by organization admins"
on public.combo_components for select to authenticated
using (public.is_platform_owner() or public.is_organization_admin(organization_id));
drop policy if exists "Combo components insertable by organization admins" on public.combo_components;
create policy "Combo components insertable by organization admins"
on public.combo_components for insert to authenticated
with check (public.is_platform_owner() or public.is_organization_admin(organization_id));
drop policy if exists "Combo components updatable by organization admins" on public.combo_components;
create policy "Combo components updatable by organization admins"
on public.combo_components for update to authenticated
using (public.is_platform_owner() or public.is_organization_admin(organization_id))
with check (public.is_platform_owner() or public.is_organization_admin(organization_id));
drop policy if exists "Combo components deletable by organization admins" on public.combo_components;
create policy "Combo components deletable by organization admins"
on public.combo_components for delete to authenticated
using (public.is_platform_owner() or public.is_organization_admin(organization_id));

grant select on public.product_stock_balances to authenticated;
grant select on public.combo_availability to authenticated;
grant select on public.employee_combos to authenticated;
grant execute on function public.calculate_product_stock(uuid) to authenticated;
grant execute on function public.reconcile_product_stock(uuid) to authenticated;
grant execute on function public.post_stock_document(uuid) to authenticated;
grant execute on function public.cancel_stock_document(uuid, text) to authenticated;
grant execute on function public.create_opening_stock_document(uuid, numeric, numeric, text) to authenticated;
grant execute on function public.set_combo_status(uuid, public.combo_status) to authenticated;
