-- Orders, timed sessions, reservations, payments, and adjustment requests.
-- No secrets, service-role keys, real emails, or destructive operations are stored here.

do $$
begin
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'order_status') then
    create type public.order_status as enum ('open', 'waiting_payment', 'paid', 'unpaid', 'payment_refused', 'cancelled');
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'order_item_type') then
    create type public.order_item_type as enum ('product', 'service', 'combo', 'timed_session', 'manual_item');
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'order_item_status') then
    create type public.order_item_status as enum ('active', 'removal_requested', 'removed', 'cancelled');
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'timed_session_status') then
    create type public.timed_session_status as enum ('active', 'completed', 'cancelled');
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'payment_method') then
    create type public.payment_method as enum ('cash', 'card_transfer');
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'payment_status') then
    create type public.payment_status as enum ('pending', 'completed', 'cancelled', 'refunded');
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'adjustment_request_status') then
    create type public.adjustment_request_status as enum ('pending', 'approved', 'rejected', 'expired', 'cancelled');
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'adjustment_request_type') then
    create type public.adjustment_request_type as enum (
      'remove_order_item',
      'change_quantity',
      'cancel_order',
      'change_payment_method',
      'correct_session_time',
      'other'
    );
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'stock_reservation_status') then
    create type public.stock_reservation_status as enum ('active', 'released', 'consumed', 'cancelled');
  end if;
end
$$;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  order_number bigint generated by default as identity,
  place_id uuid references public.places(id) on delete set null,
  current_place_name_snapshot text,
  status public.order_status not null default 'open',
  customer_label text,
  comment text,
  subtotal numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,
  paid_amount numeric(14,2) not null default 0,
  unpaid_amount numeric(14,2) not null default 0,
  opened_by uuid not null references auth.users(id),
  closed_by uuid references auth.users(id),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  payment_refusal_comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_amounts_check check (subtotal >= 0 and total_amount >= 0 and paid_amount >= 0 and unpaid_amount >= 0),
  constraint orders_paid_closed_check check (status <> 'paid' or closed_at is not null),
  constraint orders_refusal_comment_check check (status <> 'payment_refused' or length(btrim(coalesce(payment_refusal_comment, ''))) > 0)
);

create index if not exists orders_organization_id_idx on public.orders (organization_id);
create index if not exists orders_organization_status_idx on public.orders (organization_id, status);
create index if not exists orders_organization_place_idx on public.orders (organization_id, place_id);
create index if not exists orders_organization_opened_at_idx on public.orders (organization_id, opened_at desc);
create index if not exists orders_opened_by_idx on public.orders (opened_by);
create index if not exists orders_order_number_idx on public.orders (order_number);
create unique index if not exists orders_one_active_place_idx
on public.orders (organization_id, place_id)
where place_id is not null and status in ('open', 'waiting_payment');

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  item_type public.order_item_type not null,
  status public.order_item_status not null default 'active',
  product_id uuid references public.products(id) on delete set null,
  service_id uuid references public.services(id) on delete set null,
  combo_id uuid references public.combos(id) on delete set null,
  timed_session_id uuid,
  name_snapshot text not null,
  description_snapshot text,
  image_path_snapshot text,
  quantity numeric(14,3) not null default 1,
  unit_price numeric(14,2) not null,
  total_price numeric(14,2) not null,
  unit_cost_snapshot numeric(14,4),
  total_cost_snapshot numeric(14,2),
  metadata jsonb not null default '{}'::jsonb,
  added_by uuid not null references auth.users(id),
  added_at timestamptz not null default now(),
  removed_by uuid references auth.users(id),
  removed_at timestamptz,
  removal_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_items_quantity_check check (quantity > 0),
  constraint order_items_price_check check (unit_price >= 0 and total_price >= 0),
  constraint order_items_cost_check check (
    (unit_cost_snapshot is null or unit_cost_snapshot >= 0)
    and (total_cost_snapshot is null or total_cost_snapshot >= 0)
  ),
  constraint order_items_shape_check check (
    (item_type = 'product' and product_id is not null and service_id is null and combo_id is null and timed_session_id is null)
    or (item_type = 'service' and service_id is not null and product_id is null and combo_id is null and timed_session_id is null)
    or (item_type = 'combo' and combo_id is not null and product_id is null and service_id is null and timed_session_id is null)
    or (item_type = 'timed_session' and timed_session_id is not null and product_id is null and service_id is null and combo_id is null)
    or (item_type = 'manual_item' and product_id is null and service_id is null and combo_id is null and timed_session_id is null)
  )
);

create index if not exists order_items_organization_id_idx on public.order_items (organization_id);
create index if not exists order_items_order_id_idx on public.order_items (order_id);
create index if not exists order_items_order_status_idx on public.order_items (order_id, status);
create index if not exists order_items_product_id_idx on public.order_items (product_id);
create index if not exists order_items_service_id_idx on public.order_items (service_id);
create index if not exists order_items_combo_id_idx on public.order_items (combo_id);

create table if not exists public.order_combo_components (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  order_item_id uuid not null references public.order_items(id) on delete cascade,
  component_type public.combo_component_type not null,
  product_id uuid references public.products(id) on delete set null,
  service_id uuid references public.services(id) on delete set null,
  name_snapshot text not null,
  quantity numeric(14,3) not null,
  unit_price_snapshot numeric(14,2),
  unit_cost_snapshot numeric(14,4),
  included_minutes integer,
  created_at timestamptz not null default now(),
  constraint order_combo_components_quantity_check check (quantity > 0),
  constraint order_combo_components_price_check check (unit_price_snapshot is null or unit_price_snapshot >= 0),
  constraint order_combo_components_cost_check check (unit_cost_snapshot is null or unit_cost_snapshot >= 0),
  constraint order_combo_components_shape_check check (
    (component_type = 'product' and product_id is not null and service_id is null)
    or (component_type = 'service' and service_id is not null and product_id is null)
  )
);

create index if not exists order_combo_components_organization_id_idx on public.order_combo_components (organization_id);
create index if not exists order_combo_components_order_item_id_idx on public.order_combo_components (order_item_id);

create table if not exists public.timed_sessions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  place_id uuid not null references public.places(id) on delete restrict,
  service_id uuid references public.services(id) on delete set null,
  status public.timed_session_status not null default 'active',
  place_name_snapshot text not null,
  service_name_snapshot text,
  hourly_rate_snapshot numeric(14,2) not null,
  minimum_minutes_snapshot integer not null,
  billing_step_minutes_snapshot integer not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  actual_minutes integer,
  billable_minutes integer,
  calculated_amount numeric(14,2),
  started_by uuid not null references auth.users(id),
  ended_by uuid references auth.users(id),
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint timed_sessions_rate_check check (hourly_rate_snapshot > 0),
  constraint timed_sessions_minutes_check check (minimum_minutes_snapshot > 0 and billing_step_minutes_snapshot > 0),
  constraint timed_sessions_calculation_check check (
    (actual_minutes is null or actual_minutes >= 0)
    and (billable_minutes is null or billable_minutes >= 0)
    and (calculated_amount is null or calculated_amount >= 0)
  ),
  constraint timed_sessions_completed_check check (status <> 'completed' or ended_at is not null)
);

create unique index if not exists timed_sessions_one_active_place_idx
on public.timed_sessions (organization_id, place_id)
where status = 'active';
create index if not exists timed_sessions_organization_id_idx on public.timed_sessions (organization_id);
create index if not exists timed_sessions_order_id_idx on public.timed_sessions (order_id);
create index if not exists timed_sessions_status_idx on public.timed_sessions (organization_id, status);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where connamespace = 'public'::regnamespace
      and conname = 'order_items_timed_session_id_fkey'
  ) then
    alter table public.order_items
      add constraint order_items_timed_session_id_fkey
      foreign key (timed_session_id) references public.timed_sessions(id) on delete set null;
  end if;
end
$$;

create table if not exists public.stock_reservations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  order_item_id uuid not null references public.order_items(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  quantity numeric(14,3) not null,
  status public.stock_reservation_status not null default 'active',
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  released_at timestamptz,
  consumed_at timestamptz,
  constraint stock_reservations_quantity_check check (quantity > 0)
);

create index if not exists stock_reservations_organization_id_idx on public.stock_reservations (organization_id);
create index if not exists stock_reservations_product_status_idx on public.stock_reservations (product_id, status);
create index if not exists stock_reservations_order_id_idx on public.stock_reservations (order_id);
create index if not exists stock_reservations_order_item_id_idx on public.stock_reservations (order_item_id);

create table if not exists public.order_place_history (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  from_place_id uuid references public.places(id) on delete set null,
  to_place_id uuid references public.places(id) on delete set null,
  from_place_name_snapshot text,
  to_place_name_snapshot text,
  moved_by uuid not null references auth.users(id),
  moved_at timestamptz not null default now(),
  comment text
);

create index if not exists order_place_history_organization_id_idx on public.order_place_history (organization_id);
create index if not exists order_place_history_order_id_idx on public.order_place_history (order_id);

create table if not exists public.order_adjustment_requests (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  order_item_id uuid references public.order_items(id) on delete set null,
  request_type public.adjustment_request_type not null,
  status public.adjustment_request_status not null default 'pending',
  requested_quantity numeric(14,3),
  reason text not null,
  requested_by uuid not null references auth.users(id),
  requested_at timestamptz not null default now(),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  review_comment text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  constraint order_adjustment_requests_reason_check check (length(btrim(reason)) > 0),
  constraint order_adjustment_requests_quantity_check check (requested_quantity is null or requested_quantity > 0)
);

create index if not exists order_adjustment_requests_organization_id_idx on public.order_adjustment_requests (organization_id);
create index if not exists order_adjustment_requests_order_id_idx on public.order_adjustment_requests (order_id);
create index if not exists order_adjustment_requests_status_idx on public.order_adjustment_requests (organization_id, status);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  method public.payment_method not null,
  status public.payment_status not null default 'pending',
  amount numeric(14,2) not null,
  received_by uuid not null references auth.users(id),
  completed_at timestamptz,
  cancelled_at timestamptz,
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payments_amount_check check (amount > 0)
);

create unique index if not exists payments_one_completed_payment_per_order_idx
on public.payments (order_id)
where status = 'completed';
create index if not exists payments_organization_id_idx on public.payments (organization_id);
create index if not exists payments_order_id_idx on public.payments (order_id);
create index if not exists payments_status_idx on public.payments (organization_id, status);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations(id) on delete cascade,
  actor_user_id uuid references auth.users(id),
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint audit_logs_action_check check (length(btrim(action)) > 0),
  constraint audit_logs_entity_type_check check (length(btrim(entity_type)) > 0)
);

create index if not exists audit_logs_organization_id_idx on public.audit_logs (organization_id);
create index if not exists audit_logs_entity_idx on public.audit_logs (entity_type, entity_id);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);

create or replace function public.current_user_primary_organization_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select om.organization_id
  from public.organization_memberships om
  join public.organizations o on o.id = om.organization_id
  join public.profiles p on p.id = om.user_id
  where om.user_id = auth.uid()
    and om.is_active = true
    and o.status = 'active'
    and p.is_active = true
  order by case om.role when 'organization_admin' then 1 else 2 end, om.created_at asc
  limit 1;
$$;

create or replace function public.can_work_with_orders(target_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_platform_owner() or public.is_organization_member(target_organization_id);
$$;

create or replace function public.log_audit(
  target_organization_id uuid,
  target_action text,
  target_entity_type text,
  target_entity_id uuid default null,
  target_metadata jsonb default '{}'::jsonb
)
returns public.audit_logs
language plpgsql
security definer
set search_path = public
as $$
declare
  log_row public.audit_logs;
begin
  insert into public.audit_logs (
    organization_id,
    actor_user_id,
    action,
    entity_type,
    entity_id,
    metadata
  )
  values (
    target_organization_id,
    auth.uid(),
    target_action,
    target_entity_type,
    target_entity_id,
    coalesce(target_metadata, '{}'::jsonb)
  )
  returning * into log_row;

  return log_row;
end;
$$;

create or replace function public.prevent_order_direct_write()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'Physical delete is not allowed for order records.';
  end if;

  if current_setting('app.order_write', true) <> '1' then
    raise exception 'Order records can be changed only through order RPC functions.';
  end if;

  return new;
end;
$$;

create or replace function public.assert_order_place_scope()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.place_id is not null and not exists (
    select 1
    from public.places p
    where p.id = new.place_id
      and p.organization_id = new.organization_id
      and p.status = 'active'
  ) then
    raise exception 'Place does not belong to this organization or is not active.';
  end if;

  return new;
end;
$$;

create or replace function public.assert_order_item_scope()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.orders o
    where o.id = new.order_id
      and o.organization_id = new.organization_id
  ) then
    raise exception 'Order item does not belong to this order organization.';
  end if;

  return new;
end;
$$;

create or replace function public.recalculate_order_totals(target_order_id uuid)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.orders;
  next_subtotal numeric(14,2);
  next_paid numeric(14,2);
begin
  select * into order_row from public.orders where id = target_order_id for update;
  if order_row.id is null then raise exception 'Order was not found.'; end if;

  if current_setting('app.order_write', true) <> '1'
    and not public.is_organization_admin(order_row.organization_id)
  then
    raise exception 'Only trusted order functions can recalculate totals.';
  end if;

  select coalesce(sum(total_price), 0)::numeric(14,2)
  into next_subtotal
  from public.order_items
  where order_id = target_order_id
    and status = 'active';

  select coalesce(sum(amount), 0)::numeric(14,2)
  into next_paid
  from public.payments
  where order_id = target_order_id
    and status = 'completed';

  perform set_config('app.order_write', '1', true);

  update public.orders
  set
    subtotal = next_subtotal,
    total_amount = next_subtotal,
    paid_amount = next_paid,
    unpaid_amount = greatest(next_subtotal - next_paid, 0),
    updated_at = now()
  where id = target_order_id
  returning * into order_row;

  return order_row;
end;
$$;

create or replace function public.calculate_available_product_stock(target_product_id uuid)
returns numeric
language sql
stable
security definer
set search_path = public
as $$
  select (
    public.calculate_product_stock(target_product_id)
    - coalesce((
      select sum(sr.quantity)
      from public.stock_reservations sr
      where sr.product_id = target_product_id
        and sr.status = 'active'
    ), 0)
  )::numeric;
$$;

create or replace function public.release_order_item_reservations(
  target_order_item_id uuid,
  target_status public.stock_reservation_status default 'released'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform set_config('app.order_write', '1', true);

  update public.stock_reservations
  set
    status = target_status,
    released_at = case when target_status in ('released', 'cancelled') then coalesce(released_at, now()) else released_at end,
    consumed_at = case when target_status = 'consumed' then coalesce(consumed_at, now()) else consumed_at end
  where order_item_id = target_order_item_id
    and status = 'active';
end;
$$;

create or replace function public.create_order(
  target_place_id uuid default null,
  target_customer_label text default null,
  target_comment text default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  target_organization_id uuid;
  place_row public.places;
  order_row public.orders;
begin
  if target_place_id is not null then
    select * into place_row from public.places where id = target_place_id for update;
    if place_row.id is null then raise exception 'Place was not found.'; end if;
    if place_row.status <> 'active' then raise exception 'Place is not active.'; end if;
    target_organization_id := place_row.organization_id;
  else
    target_organization_id := public.current_user_primary_organization_id();
  end if;

  if target_organization_id is null then
    raise exception 'Organization could not be determined.';
  end if;

  if not public.can_work_with_orders(target_organization_id) then
    raise exception 'You do not have access to this organization.';
  end if;

  if not exists (select 1 from public.organizations o where o.id = target_organization_id and o.status = 'active') then
    raise exception 'Organization is not active.';
  end if;

  if target_place_id is not null then
    if exists (
      select 1 from public.orders o
      where o.organization_id = target_organization_id
        and o.place_id = target_place_id
        and o.status in ('open', 'waiting_payment')
    ) then
      raise exception 'Place already has an active order.';
    end if;

    if exists (
      select 1 from public.timed_sessions ts
      where ts.organization_id = target_organization_id
        and ts.place_id = target_place_id
        and ts.status = 'active'
    ) then
      raise exception 'Place already has an active timed session.';
    end if;
  end if;

  perform set_config('app.order_write', '1', true);

  insert into public.orders (
    organization_id,
    place_id,
    current_place_name_snapshot,
    customer_label,
    comment,
    opened_by
  )
  values (
    target_organization_id,
    target_place_id,
    place_row.name,
    nullif(btrim(target_customer_label), ''),
    nullif(btrim(target_comment), ''),
    auth.uid()
  )
  returning * into order_row;

  perform public.log_audit(target_organization_id, 'order.created', 'order', order_row.id, jsonb_build_object('place_id', target_place_id));

  return order_row;
end;
$$;

create or replace function public.add_product_to_order(
  target_order_id uuid,
  target_product_id uuid,
  target_quantity numeric
)
returns public.order_items
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.orders;
  product_row public.products;
  item_row public.order_items;
  existing_item_id uuid;
  next_quantity numeric(14,3);
  available_quantity numeric;
begin
  if target_quantity <= 0 then raise exception 'Quantity must be greater than zero.'; end if;

  select * into order_row from public.orders where id = target_order_id for update;
  if order_row.id is null then raise exception 'Order was not found.'; end if;
  if order_row.status <> 'open' then raise exception 'Only open orders can be changed.'; end if;
  if not public.can_work_with_orders(order_row.organization_id) then raise exception 'You do not have access to this order.'; end if;

  select * into product_row from public.products where id = target_product_id for update;
  if product_row.id is null then raise exception 'Product was not found.'; end if;
  if product_row.organization_id <> order_row.organization_id or product_row.status <> 'active' then
    raise exception 'Product is not active in this organization.';
  end if;

  if product_row.track_stock then
    available_quantity := public.calculate_available_product_stock(product_row.id);
    if available_quantity < target_quantity then
      raise exception 'Not enough available stock for product %. Available: %.', product_row.name, available_quantity;
    end if;
  end if;

  perform set_config('app.order_write', '1', true);

  select id into existing_item_id
  from public.order_items
  where order_id = order_row.id
    and item_type = 'product'
    and product_id = product_row.id
    and status = 'active'
  order by added_at asc
  limit 1
  for update;

  if existing_item_id is null then
    insert into public.order_items (
      organization_id,
      order_id,
      item_type,
      product_id,
      name_snapshot,
      description_snapshot,
      image_path_snapshot,
      quantity,
      unit_price,
      total_price,
      unit_cost_snapshot,
      total_cost_snapshot,
      added_by
    )
    values (
      order_row.organization_id,
      order_row.id,
      'product',
      product_row.id,
      product_row.name,
      product_row.description,
      product_row.image_path,
      target_quantity,
      product_row.sale_price,
      product_row.sale_price * target_quantity,
      product_row.average_purchase_cost,
      product_row.average_purchase_cost * target_quantity,
      auth.uid()
    )
    returning * into item_row;
  else
    update public.order_items
    set
      quantity = quantity + target_quantity,
      total_price = unit_price * (quantity + target_quantity),
      total_cost_snapshot = coalesce(unit_cost_snapshot, 0) * (quantity + target_quantity),
      updated_at = now()
    where id = existing_item_id
    returning * into item_row;
  end if;

  if product_row.track_stock then
    insert into public.stock_reservations (
      organization_id,
      order_id,
      order_item_id,
      product_id,
      quantity,
      created_by
    )
    values (
      order_row.organization_id,
      order_row.id,
      item_row.id,
      product_row.id,
      target_quantity,
      auth.uid()
    );
  end if;

  perform public.recalculate_order_totals(order_row.id);
  perform public.log_audit(order_row.organization_id, 'order.item_added', 'order_item', item_row.id, jsonb_build_object('type', 'product', 'product_id', product_row.id, 'quantity', target_quantity));

  return item_row;
end;
$$;

create or replace function public.add_service_to_order(
  target_order_id uuid,
  target_service_id uuid,
  target_quantity numeric default 1
)
returns public.order_items
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.orders;
  service_row public.services;
  item_row public.order_items;
  existing_item_id uuid;
begin
  if target_quantity <= 0 then raise exception 'Quantity must be greater than zero.'; end if;

  select * into order_row from public.orders where id = target_order_id for update;
  if order_row.id is null then raise exception 'Order was not found.'; end if;
  if order_row.status <> 'open' then raise exception 'Only open orders can be changed.'; end if;
  if not public.can_work_with_orders(order_row.organization_id) then raise exception 'You do not have access to this order.'; end if;

  select * into service_row from public.services where id = target_service_id;
  if service_row.id is null then raise exception 'Service was not found.'; end if;
  if service_row.organization_id <> order_row.organization_id or service_row.status <> 'active' then
    raise exception 'Service is not active in this organization.';
  end if;
  if service_row.pricing_type <> 'fixed' then
    raise exception 'Hourly services must be added through timed sessions.';
  end if;

  perform set_config('app.order_write', '1', true);

  select id into existing_item_id
  from public.order_items
  where order_id = order_row.id
    and item_type = 'service'
    and service_id = service_row.id
    and status = 'active'
  order by added_at asc
  limit 1
  for update;

  if existing_item_id is null then
    insert into public.order_items (
      organization_id,
      order_id,
      item_type,
      service_id,
      name_snapshot,
      description_snapshot,
      image_path_snapshot,
      quantity,
      unit_price,
      total_price,
      added_by
    )
    values (
      order_row.organization_id,
      order_row.id,
      'service',
      service_row.id,
      service_row.name,
      service_row.description,
      service_row.image_path,
      target_quantity,
      service_row.fixed_price,
      service_row.fixed_price * target_quantity,
      auth.uid()
    )
    returning * into item_row;
  else
    update public.order_items
    set
      quantity = quantity + target_quantity,
      total_price = unit_price * (quantity + target_quantity),
      updated_at = now()
    where id = existing_item_id
    returning * into item_row;
  end if;

  perform public.recalculate_order_totals(order_row.id);
  perform public.log_audit(order_row.organization_id, 'order.item_added', 'order_item', item_row.id, jsonb_build_object('type', 'service', 'service_id', service_row.id, 'quantity', target_quantity));

  return item_row;
end;
$$;

create or replace function public.add_combo_to_order(
  target_order_id uuid,
  target_combo_id uuid,
  target_quantity numeric default 1
)
returns public.order_items
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.orders;
  combo_row public.combos;
  component_row public.combo_components;
  product_row public.products;
  service_row public.services;
  item_row public.order_items;
  required_quantity numeric(14,3);
  available_quantity numeric;
  component_cost numeric(14,4);
  total_cost numeric(14,2) := 0;
begin
  if target_quantity <= 0 then raise exception 'Quantity must be greater than zero.'; end if;

  select * into order_row from public.orders where id = target_order_id for update;
  if order_row.id is null then raise exception 'Order was not found.'; end if;
  if order_row.status <> 'open' then raise exception 'Only open orders can be changed.'; end if;
  if not public.can_work_with_orders(order_row.organization_id) then raise exception 'You do not have access to this order.'; end if;

  select * into combo_row from public.combos where id = target_combo_id;
  if combo_row.id is null then raise exception 'Combo was not found.'; end if;
  if combo_row.organization_id <> order_row.organization_id or combo_row.status <> 'active' then
    raise exception 'Combo is not active in this organization.';
  end if;
  if combo_row.selection_mode <> 'fixed' then
    raise exception 'Only fixed combos are supported at this stage.';
  end if;

  for component_row in
    select * from public.combo_components
    where combo_id = combo_row.id
    order by sort_order asc, created_at asc
  loop
    if component_row.component_type = 'product' then
      select * into product_row from public.products where id = component_row.product_id for update;
      if product_row.id is null or product_row.status <> 'active' or product_row.organization_id <> order_row.organization_id then
        raise exception 'Combo product component is not active.';
      end if;

      required_quantity := component_row.quantity * target_quantity;
      if product_row.track_stock then
        available_quantity := public.calculate_available_product_stock(product_row.id);
        if available_quantity < required_quantity then
          raise exception 'Not enough available stock for combo component %. Available: %.', product_row.name, available_quantity;
        end if;
      end if;

      total_cost := total_cost + (product_row.average_purchase_cost * required_quantity);
    end if;
  end loop;

  perform set_config('app.order_write', '1', true);

  insert into public.order_items (
    organization_id,
    order_id,
    item_type,
    combo_id,
    name_snapshot,
    description_snapshot,
    image_path_snapshot,
    quantity,
    unit_price,
    total_price,
    unit_cost_snapshot,
    total_cost_snapshot,
    metadata,
    added_by
  )
  values (
    order_row.organization_id,
    order_row.id,
    'combo',
    combo_row.id,
    combo_row.name,
    combo_row.description,
    combo_row.image_path,
    target_quantity,
    combo_row.sale_price,
    combo_row.sale_price * target_quantity,
    case when target_quantity > 0 then total_cost / target_quantity else 0 end,
    total_cost,
    jsonb_build_object('selection_mode', combo_row.selection_mode),
    auth.uid()
  )
  returning * into item_row;

  for component_row in
    select * from public.combo_components
    where combo_id = combo_row.id
    order by sort_order asc, created_at asc
  loop
    if component_row.component_type = 'product' then
      select * into product_row from public.products where id = component_row.product_id;
      component_cost := product_row.average_purchase_cost;

      insert into public.order_combo_components (
        organization_id,
        order_item_id,
        component_type,
        product_id,
        name_snapshot,
        quantity,
        unit_price_snapshot,
        unit_cost_snapshot,
        included_minutes
      )
      values (
        order_row.organization_id,
        item_row.id,
        'product',
        product_row.id,
        product_row.name,
        component_row.quantity,
        product_row.sale_price,
        component_cost,
        component_row.included_minutes
      );

      if product_row.track_stock then
        insert into public.stock_reservations (
          organization_id,
          order_id,
          order_item_id,
          product_id,
          quantity,
          created_by
        )
        values (
          order_row.organization_id,
          order_row.id,
          item_row.id,
          product_row.id,
          component_row.quantity * target_quantity,
          auth.uid()
        );
      end if;
    else
      select * into service_row from public.services where id = component_row.service_id;

      insert into public.order_combo_components (
        organization_id,
        order_item_id,
        component_type,
        service_id,
        name_snapshot,
        quantity,
        unit_price_snapshot,
        included_minutes
      )
      values (
        order_row.organization_id,
        item_row.id,
        'service',
        service_row.id,
        service_row.name,
        component_row.quantity,
        coalesce(service_row.fixed_price, service_row.hourly_rate, 0),
        component_row.included_minutes
      );
    end if;
  end loop;

  perform public.recalculate_order_totals(order_row.id);
  perform public.log_audit(order_row.organization_id, 'order.item_added', 'order_item', item_row.id, jsonb_build_object('type', 'combo', 'combo_id', combo_row.id, 'quantity', target_quantity));

  return item_row;
end;
$$;

create or replace function public.start_timed_session(
  target_place_id uuid,
  target_order_id uuid default null
)
returns public.timed_sessions
language plpgsql
security definer
set search_path = public
as $$
declare
  place_row public.places;
  order_row public.orders;
  session_row public.timed_sessions;
begin
  select * into place_row from public.places where id = target_place_id for update;
  if place_row.id is null then raise exception 'Place was not found.'; end if;
  if place_row.status <> 'active' or place_row.has_timer = false then raise exception 'Place is not an active timed place.'; end if;
  if not public.can_work_with_orders(place_row.organization_id) then raise exception 'You do not have access to this place.'; end if;
  if coalesce(place_row.hourly_rate, 0) <= 0 or coalesce(place_row.minimum_minutes, 0) <= 0 or coalesce(place_row.billing_step_minutes, 0) <= 0 then
    raise exception 'Timed place tariff is incomplete.';
  end if;

  if exists (select 1 from public.timed_sessions where organization_id = place_row.organization_id and place_id = place_row.id and status = 'active') then
    raise exception 'Place already has an active timed session.';
  end if;

  perform set_config('app.order_write', '1', true);

  if target_order_id is null then
    insert into public.orders (
      organization_id,
      place_id,
      current_place_name_snapshot,
      opened_by
    )
    values (
      place_row.organization_id,
      place_row.id,
      place_row.name,
      auth.uid()
    )
    returning * into order_row;
  else
    select * into order_row from public.orders where id = target_order_id for update;
    if order_row.id is null then raise exception 'Order was not found.'; end if;
    if order_row.organization_id <> place_row.organization_id then raise exception 'Order and place belong to different organizations.'; end if;
    if order_row.status <> 'open' then raise exception 'Only open orders can receive timed sessions.'; end if;
    if exists (select 1 from public.timed_sessions where order_id = order_row.id and status = 'active') then
      raise exception 'Order already has an active timed session.';
    end if;

    update public.orders
    set
      place_id = place_row.id,
      current_place_name_snapshot = place_row.name,
      updated_at = now()
    where id = order_row.id
    returning * into order_row;
  end if;

  insert into public.timed_sessions (
    organization_id,
    order_id,
    place_id,
    place_name_snapshot,
    hourly_rate_snapshot,
    minimum_minutes_snapshot,
    billing_step_minutes_snapshot,
    started_by
  )
  values (
    place_row.organization_id,
    order_row.id,
    place_row.id,
    place_row.name,
    place_row.hourly_rate,
    place_row.minimum_minutes,
    place_row.billing_step_minutes,
    auth.uid()
  )
  returning * into session_row;

  perform public.log_audit(place_row.organization_id, 'session.started', 'timed_session', session_row.id, jsonb_build_object('order_id', order_row.id, 'place_id', place_row.id));

  return session_row;
end;
$$;

create or replace function public.complete_timed_session(target_session_id uuid)
returns public.timed_sessions
language plpgsql
security definer
set search_path = public
as $$
declare
  session_row public.timed_sessions;
  actual integer;
  billable integer;
  amount numeric(14,2);
  existing_item_id uuid;
begin
  select * into session_row from public.timed_sessions where id = target_session_id for update;
  if session_row.id is null then raise exception 'Timed session was not found.'; end if;
  if not public.can_work_with_orders(session_row.organization_id) then raise exception 'You do not have access to this session.'; end if;
  if session_row.status = 'completed' then return session_row; end if;
  if session_row.status <> 'active' then raise exception 'Only active sessions can be completed.'; end if;

  actual := greatest(1, ceil(extract(epoch from (now() - session_row.started_at)) / 60.0)::integer);
  if actual <= session_row.minimum_minutes_snapshot then
    billable := session_row.minimum_minutes_snapshot;
  else
    billable := session_row.minimum_minutes_snapshot
      + ceil((actual - session_row.minimum_minutes_snapshot)::numeric / session_row.billing_step_minutes_snapshot)::integer
      * session_row.billing_step_minutes_snapshot;
  end if;
  amount := round((session_row.hourly_rate_snapshot * billable / 60.0)::numeric, 2);

  perform set_config('app.order_write', '1', true);

  update public.timed_sessions
  set
    status = 'completed',
    ended_at = now(),
    actual_minutes = actual,
    billable_minutes = billable,
    calculated_amount = amount,
    ended_by = auth.uid(),
    updated_at = now()
  where id = session_row.id
  returning * into session_row;

  select id into existing_item_id
  from public.order_items
  where timed_session_id = session_row.id
  limit 1;

  if existing_item_id is null then
    insert into public.order_items (
      organization_id,
      order_id,
      item_type,
      timed_session_id,
      name_snapshot,
      description_snapshot,
      quantity,
      unit_price,
      total_price,
      metadata,
      added_by
    )
    values (
      session_row.organization_id,
      session_row.order_id,
      'timed_session',
      session_row.id,
      session_row.place_name_snapshot,
      session_row.service_name_snapshot,
      1,
      amount,
      amount,
      jsonb_build_object('actual_minutes', actual, 'billable_minutes', billable, 'hourly_rate', session_row.hourly_rate_snapshot),
      auth.uid()
    );
  end if;

  perform public.recalculate_order_totals(session_row.order_id);
  perform public.log_audit(session_row.organization_id, 'session.completed', 'timed_session', session_row.id, jsonb_build_object('order_id', session_row.order_id, 'amount', amount, 'billable_minutes', billable));

  return session_row;
end;
$$;

create or replace function public.move_open_order_to_place(
  target_order_id uuid,
  target_place_id uuid,
  target_comment text default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.orders;
  target_place public.places;
  from_place public.places;
begin
  select * into order_row from public.orders where id = target_order_id for update;
  if order_row.id is null then raise exception 'Order was not found.'; end if;
  if order_row.status <> 'open' then raise exception 'Only open orders can be moved.'; end if;
  if not public.can_work_with_orders(order_row.organization_id) then raise exception 'You do not have access to this order.'; end if;
  if exists (select 1 from public.timed_sessions where order_id = order_row.id and status = 'active') then
    raise exception 'Order has an active timed session.';
  end if;

  select * into target_place from public.places where id = target_place_id for update;
  if target_place.id is null then raise exception 'Target place was not found.'; end if;
  if target_place.organization_id <> order_row.organization_id or target_place.status <> 'active' then
    raise exception 'Target place is not active in this organization.';
  end if;
  if exists (
    select 1 from public.orders
    where organization_id = order_row.organization_id
      and place_id = target_place.id
      and status in ('open', 'waiting_payment')
      and id <> order_row.id
  ) then
    raise exception 'Target place already has an active order.';
  end if;
  if exists (select 1 from public.timed_sessions where organization_id = order_row.organization_id and place_id = target_place.id and status = 'active') then
    raise exception 'Target place already has an active timed session.';
  end if;

  if order_row.place_id is not null then
    select * into from_place from public.places where id = order_row.place_id;
  end if;

  perform set_config('app.order_write', '1', true);

  insert into public.order_place_history (
    organization_id,
    order_id,
    from_place_id,
    to_place_id,
    from_place_name_snapshot,
    to_place_name_snapshot,
    moved_by,
    comment
  )
  values (
    order_row.organization_id,
    order_row.id,
    order_row.place_id,
    target_place.id,
    coalesce(order_row.current_place_name_snapshot, from_place.name),
    target_place.name,
    auth.uid(),
    nullif(btrim(target_comment), '')
  );

  update public.orders
  set
    place_id = target_place.id,
    current_place_name_snapshot = target_place.name,
    updated_at = now()
  where id = order_row.id
  returning * into order_row;

  perform public.log_audit(order_row.organization_id, 'order.moved', 'order', order_row.id, jsonb_build_object('to_place_id', target_place.id));

  return order_row;
end;
$$;

create or replace function public.request_order_adjustment(
  target_order_id uuid,
  target_order_item_id uuid default null,
  target_request_type public.adjustment_request_type default 'other',
  target_reason text default null,
  target_requested_quantity numeric default null
)
returns public.order_adjustment_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.orders;
  item_row public.order_items;
  request_row public.order_adjustment_requests;
begin
  if length(btrim(coalesce(target_reason, ''))) = 0 then raise exception 'Reason is required.'; end if;

  select * into order_row from public.orders where id = target_order_id;
  if order_row.id is null then raise exception 'Order was not found.'; end if;
  if order_row.status not in ('open', 'waiting_payment') then raise exception 'Only active orders can be corrected.'; end if;
  if not public.can_work_with_orders(order_row.organization_id) then raise exception 'You do not have access to this order.'; end if;

  if target_order_item_id is not null then
    select * into item_row from public.order_items where id = target_order_item_id and order_id = order_row.id;
    if item_row.id is null then raise exception 'Order item was not found.'; end if;
  end if;

  perform set_config('app.order_write', '1', true);

  insert into public.order_adjustment_requests (
    organization_id,
    order_id,
    order_item_id,
    request_type,
    requested_quantity,
    reason,
    requested_by,
    expires_at
  )
  values (
    order_row.organization_id,
    order_row.id,
    target_order_item_id,
    target_request_type,
    target_requested_quantity,
    target_reason,
    auth.uid(),
    now() + interval '24 hours'
  )
  returning * into request_row;

  perform public.log_audit(order_row.organization_id, 'adjustment.requested', 'order_adjustment_request', request_row.id, jsonb_build_object('type', target_request_type, 'order_id', order_row.id));

  return request_row;
end;
$$;

create or replace function public.review_order_adjustment(
  target_request_id uuid,
  target_decision text,
  target_comment text default null
)
returns public.order_adjustment_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  request_row public.order_adjustment_requests;
  item_row public.order_items;
  order_row public.orders;
  product_row public.products;
  delta numeric(14,3);
  available_quantity numeric;
begin
  if target_decision not in ('approved', 'rejected') then raise exception 'Decision must be approved or rejected.'; end if;

  select * into request_row from public.order_adjustment_requests where id = target_request_id for update;
  if request_row.id is null then raise exception 'Adjustment request was not found.'; end if;
  if request_row.status <> 'pending' then raise exception 'Adjustment request is already reviewed.'; end if;
  if not public.is_organization_admin(request_row.organization_id) then raise exception 'Only organization admins can review adjustment requests.'; end if;

  select * into order_row from public.orders where id = request_row.order_id for update;
  if order_row.id is null then raise exception 'Order was not found.'; end if;
  if order_row.status not in ('open', 'waiting_payment') then raise exception 'Only active orders can be corrected.'; end if;

  perform set_config('app.order_write', '1', true);

  if target_decision = 'approved' then
    if request_row.request_type = 'remove_order_item' then
      select * into item_row from public.order_items where id = request_row.order_item_id for update;
      if item_row.id is null then raise exception 'Order item was not found.'; end if;
      if item_row.status <> 'active' then raise exception 'Only active items can be removed.'; end if;

      update public.order_items
      set status = 'removed', removed_by = auth.uid(), removed_at = now(), removal_reason = request_row.reason, updated_at = now()
      where id = item_row.id;

      perform public.release_order_item_reservations(item_row.id, 'released');
      perform public.recalculate_order_totals(order_row.id);
    elsif request_row.request_type = 'change_quantity' then
      select * into item_row from public.order_items where id = request_row.order_item_id for update;
      if item_row.id is null then raise exception 'Order item was not found.'; end if;
      if item_row.status <> 'active' then raise exception 'Only active items can be changed.'; end if;
      if request_row.requested_quantity is null or request_row.requested_quantity <= 0 then raise exception 'Requested quantity is required.'; end if;
      if item_row.item_type = 'timed_session' then raise exception 'Timed session item quantity cannot be changed.'; end if;

      delta := request_row.requested_quantity - item_row.quantity;
      if delta > 0 and item_row.item_type = 'product' then
        select * into product_row from public.products where id = item_row.product_id for update;
        if product_row.track_stock then
          available_quantity := public.calculate_available_product_stock(product_row.id);
          if available_quantity < delta then
            raise exception 'Not enough available stock for quantity increase.';
          end if;
          insert into public.stock_reservations (organization_id, order_id, order_item_id, product_id, quantity, created_by)
          values (item_row.organization_id, item_row.order_id, item_row.id, product_row.id, delta, auth.uid());
        end if;
      elsif delta < 0 then
        update public.stock_reservations
        set quantity = greatest(quantity + delta, 0)
        where order_item_id = item_row.id
          and status = 'active';

        update public.stock_reservations
        set status = 'released', released_at = now()
        where order_item_id = item_row.id
          and status = 'active'
          and quantity <= 0;
      end if;

      update public.order_items
      set
        quantity = request_row.requested_quantity,
        total_price = unit_price * request_row.requested_quantity,
        total_cost_snapshot = coalesce(unit_cost_snapshot, 0) * request_row.requested_quantity,
        updated_at = now()
      where id = item_row.id;

      perform public.recalculate_order_totals(order_row.id);
    elsif request_row.request_type = 'cancel_order' then
      update public.order_items
      set status = 'cancelled', removed_by = auth.uid(), removed_at = now(), removal_reason = request_row.reason, updated_at = now()
      where order_id = order_row.id
        and status = 'active';

      update public.stock_reservations
      set status = 'cancelled', released_at = now()
      where order_id = order_row.id
        and status = 'active';

      update public.orders
      set status = 'cancelled', closed_by = auth.uid(), closed_at = now(), updated_at = now()
      where id = order_row.id;
    end if;
  end if;

  update public.order_adjustment_requests
  set
    status = target_decision::public.adjustment_request_status,
    reviewed_by = auth.uid(),
    reviewed_at = now(),
    review_comment = nullif(btrim(target_comment), '')
  where id = request_row.id
  returning * into request_row;

  perform public.log_audit(request_row.organization_id, 'adjustment.' || target_decision, 'order_adjustment_request', request_row.id, jsonb_build_object('order_id', request_row.order_id));

  return request_row;
end;
$$;

create or replace function public.set_order_waiting_payment(target_order_id uuid)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.orders;
begin
  select * into order_row from public.orders where id = target_order_id for update;
  if order_row.id is null then raise exception 'Order was not found.'; end if;
  if order_row.status <> 'open' then raise exception 'Only open orders can wait for payment.'; end if;
  if not public.can_work_with_orders(order_row.organization_id) then raise exception 'You do not have access to this order.'; end if;
  if exists (select 1 from public.timed_sessions where order_id = order_row.id and status = 'active') then
    raise exception 'Active timed session must be completed first.';
  end if;

  perform set_config('app.order_write', '1', true);

  update public.orders
  set status = 'waiting_payment', updated_at = now()
  where id = order_row.id
  returning * into order_row;

  return order_row;
end;
$$;

create or replace function public.consume_order_stock(target_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  reservation_row public.stock_reservations;
  product_row public.products;
  next_quantity numeric;
begin
  perform set_config('app.order_write', '1', true);
  perform set_config('app.inventory_write', '1', true);

  for reservation_row in
    select * from public.stock_reservations
    where order_id = target_order_id
      and status = 'active'
    order by created_at asc
    for update
  loop
    select * into product_row from public.products where id = reservation_row.product_id for update;
    next_quantity := public.calculate_product_stock(product_row.id) - reservation_row.quantity;
    if next_quantity < 0 then
      raise exception 'Stock cannot become negative for product %.', product_row.name;
    end if;

    insert into public.stock_movements (
      organization_id,
      product_id,
      movement_type,
      quantity_delta,
      unit_cost,
      total_cost,
      reference_type,
      reference_id,
      comment,
      created_by
    )
    values (
      reservation_row.organization_id,
      reservation_row.product_id,
      'sale',
      -reservation_row.quantity,
      product_row.average_purchase_cost,
      -(reservation_row.quantity * product_row.average_purchase_cost),
      'order',
      reservation_row.order_item_id,
      'Order sale',
      auth.uid()
    );

    update public.stock_reservations
    set status = 'consumed', consumed_at = now()
    where id = reservation_row.id;

    perform public.reconcile_product_stock(reservation_row.product_id);
  end loop;
end;
$$;

create or replace function public.complete_order_payment(
  target_order_id uuid,
  target_method public.payment_method
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.orders;
begin
  select * into order_row from public.orders where id = target_order_id for update;
  if order_row.id is null then raise exception 'Order was not found.'; end if;
  if order_row.status not in ('open', 'waiting_payment') then raise exception 'Order cannot be paid in current status.'; end if;
  if order_row.total_amount <= 0 then raise exception 'Order total must be greater than zero.'; end if;
  if not public.can_work_with_orders(order_row.organization_id) then raise exception 'You do not have access to this order.'; end if;
  if exists (select 1 from public.timed_sessions where order_id = order_row.id and status = 'active') then
    raise exception 'Active timed session must be completed first.';
  end if;
  if exists (select 1 from public.order_adjustment_requests where order_id = order_row.id and status = 'pending') then
    raise exception 'Pending adjustment requests must be reviewed first.';
  end if;
  if exists (select 1 from public.payments where order_id = order_row.id and status = 'completed') then
    raise exception 'Order already has completed payment.';
  end if;

  perform set_config('app.order_write', '1', true);

  insert into public.payments (
    organization_id,
    order_id,
    method,
    status,
    amount,
    received_by,
    completed_at
  )
  values (
    order_row.organization_id,
    order_row.id,
    target_method,
    'completed',
    order_row.total_amount,
    auth.uid(),
    now()
  );

  perform public.consume_order_stock(order_row.id);

  update public.orders
  set
    status = 'paid',
    paid_amount = total_amount,
    unpaid_amount = 0,
    closed_by = auth.uid(),
    closed_at = now(),
    updated_at = now()
  where id = order_row.id
  returning * into order_row;

  perform public.log_audit(order_row.organization_id, 'payment.completed', 'order', order_row.id, jsonb_build_object('method', target_method, 'amount', order_row.total_amount));

  return order_row;
end;
$$;

create or replace function public.mark_order_payment_refused(
  target_order_id uuid,
  target_comment text
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.orders;
begin
  if length(btrim(coalesce(target_comment, ''))) = 0 then raise exception 'Payment refusal comment is required.'; end if;

  select * into order_row from public.orders where id = target_order_id for update;
  if order_row.id is null then raise exception 'Order was not found.'; end if;
  if order_row.status not in ('open', 'waiting_payment') then raise exception 'Order cannot be refused in current status.'; end if;
  if not public.can_work_with_orders(order_row.organization_id) then raise exception 'You do not have access to this order.'; end if;
  if exists (select 1 from public.timed_sessions where order_id = order_row.id and status = 'active') then
    raise exception 'Active timed session must be completed first.';
  end if;

  perform set_config('app.order_write', '1', true);
  perform public.consume_order_stock(order_row.id);

  update public.orders
  set
    status = 'payment_refused',
    paid_amount = 0,
    unpaid_amount = total_amount,
    payment_refusal_comment = target_comment,
    closed_by = auth.uid(),
    closed_at = now(),
    updated_at = now()
  where id = order_row.id
  returning * into order_row;

  perform public.log_audit(order_row.organization_id, 'payment.refused', 'order', order_row.id, jsonb_build_object('amount', order_row.total_amount, 'comment', target_comment));

  return order_row;
end;
$$;

create or replace view public.combo_availability
with (security_barrier = true)
as
with product_requirements as (
  select
    c.id as combo_id,
    c.organization_id,
    cc.product_id,
    sum(cc.quantity) as required_quantity
  from public.combos c
  join public.combo_components cc on cc.combo_id = c.id
  where cc.component_type = 'product'
    and cc.is_required = true
  group by c.id, c.organization_id, cc.product_id
),
component_availability as (
  select
    pr.combo_id,
    pr.organization_id,
    pr.product_id,
    pr.required_quantity,
    p.track_stock,
    p.status as product_status,
    public.calculate_available_product_stock(pr.product_id) as current_stock,
    case
      when p.track_stock = false then null
      else floor(public.calculate_available_product_stock(pr.product_id) / pr.required_quantity)
    end as available_quantity
  from product_requirements pr
  join public.products p on p.id = pr.product_id
)
select
  c.id as combo_id,
  c.organization_id,
  (
    c.status = 'active'
    and public.is_organization_member(c.organization_id)
    and not exists (
      select 1
      from component_availability ca
      where ca.combo_id = c.id
        and ca.track_stock = true
        and (ca.product_status <> 'active' or ca.current_stock < ca.required_quantity)
    )
  ) as is_available,
  case
    when not exists (select 1 from component_availability ca where ca.combo_id = c.id and ca.track_stock = true) then null
    else (
      select min(ca.available_quantity)::integer
      from component_availability ca
      where ca.combo_id = c.id
        and ca.track_stock = true
    )
  end as available_quantity,
  coalesce((
    select jsonb_agg(jsonb_build_object(
      'product_id', ca.product_id,
      'required_quantity', ca.required_quantity,
      'current_stock', ca.current_stock
    ))
    from component_availability ca
    where ca.combo_id = c.id
      and ca.track_stock = true
      and (ca.product_status <> 'active' or ca.current_stock < ca.required_quantity)
  ), '[]'::jsonb) as missing_components
from public.combos c
where public.is_platform_owner() or public.is_organization_member(c.organization_id);

create or replace view public.employee_workspace_places
with (security_barrier = true)
as
select
  p.id,
  p.organization_id,
  p.category_id,
  p.name,
  p.type,
  p.custom_type_name,
  p.description,
  p.image_path,
  p.has_timer,
  p.hourly_rate,
  p.minimum_minutes,
  p.billing_step_minutes,
  p.capacity,
  p.sort_order,
  p.status,
  o.id as active_order_id,
  o.order_number as active_order_number,
  o.status as active_order_status,
  o.total_amount as active_order_total,
  ts.id as active_session_id,
  ts.started_at as active_session_started_at,
  ts.hourly_rate_snapshot as active_session_hourly_rate,
  ts.minimum_minutes_snapshot as active_session_minimum_minutes,
  ts.billing_step_minutes_snapshot as active_session_billing_step_minutes,
  coalesce((
    select count(*)
    from public.order_items oi
    where oi.order_id = o.id
      and oi.status = 'active'
  ), 0)::integer as active_order_item_count
from public.places p
left join public.orders o on o.place_id = p.id and o.status in ('open', 'waiting_payment')
left join public.timed_sessions ts on ts.place_id = p.id and ts.status = 'active'
where public.is_organization_member(p.organization_id);

create or replace view public.employee_orders
with (security_barrier = true)
as
select
  o.id,
  o.organization_id,
  o.order_number,
  o.place_id,
  o.current_place_name_snapshot,
  o.status,
  o.customer_label,
  o.comment,
  o.subtotal,
  o.total_amount,
  o.paid_amount,
  o.unpaid_amount,
  o.opened_by,
  o.opened_at,
  o.closed_at,
  o.payment_refusal_comment,
  o.created_at,
  o.updated_at
from public.orders o
where public.is_organization_member(o.organization_id);

create or replace view public.employee_order_items
with (security_barrier = true)
as
select
  oi.id,
  oi.organization_id,
  oi.order_id,
  oi.item_type,
  oi.status,
  oi.product_id,
  oi.service_id,
  oi.combo_id,
  oi.timed_session_id,
  oi.name_snapshot,
  oi.description_snapshot,
  oi.image_path_snapshot,
  oi.quantity,
  oi.unit_price,
  oi.total_price,
  oi.metadata,
  oi.added_by,
  oi.added_at,
  oi.removed_at,
  oi.removal_reason,
  oi.created_at,
  oi.updated_at
from public.order_items oi
where public.is_organization_member(oi.organization_id);

create or replace view public.employee_timed_sessions
with (security_barrier = true)
as
select
  ts.id,
  ts.organization_id,
  ts.order_id,
  ts.place_id,
  ts.service_id,
  ts.status,
  ts.place_name_snapshot,
  ts.service_name_snapshot,
  ts.hourly_rate_snapshot,
  ts.minimum_minutes_snapshot,
  ts.billing_step_minutes_snapshot,
  ts.started_at,
  ts.ended_at,
  ts.actual_minutes,
  ts.billable_minutes,
  ts.calculated_amount,
  ts.started_by,
  ts.ended_by,
  ts.created_at,
  ts.updated_at
from public.timed_sessions ts
where public.is_organization_member(ts.organization_id);

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();
drop trigger if exists order_items_set_updated_at on public.order_items;
create trigger order_items_set_updated_at before update on public.order_items
for each row execute function public.set_updated_at();
drop trigger if exists timed_sessions_set_updated_at on public.timed_sessions;
create trigger timed_sessions_set_updated_at before update on public.timed_sessions
for each row execute function public.set_updated_at();
drop trigger if exists payments_set_updated_at on public.payments;
create trigger payments_set_updated_at before update on public.payments
for each row execute function public.set_updated_at();

drop trigger if exists orders_direct_write_guard on public.orders;
create trigger orders_direct_write_guard before insert or update or delete on public.orders
for each row execute function public.prevent_order_direct_write();
drop trigger if exists order_items_direct_write_guard on public.order_items;
create trigger order_items_direct_write_guard before insert or update or delete on public.order_items
for each row execute function public.prevent_order_direct_write();
drop trigger if exists order_combo_components_direct_write_guard on public.order_combo_components;
create trigger order_combo_components_direct_write_guard before insert or update or delete on public.order_combo_components
for each row execute function public.prevent_order_direct_write();
drop trigger if exists timed_sessions_direct_write_guard on public.timed_sessions;
create trigger timed_sessions_direct_write_guard before insert or update or delete on public.timed_sessions
for each row execute function public.prevent_order_direct_write();
drop trigger if exists stock_reservations_direct_write_guard on public.stock_reservations;
create trigger stock_reservations_direct_write_guard before insert or update or delete on public.stock_reservations
for each row execute function public.prevent_order_direct_write();
drop trigger if exists payments_direct_write_guard on public.payments;
create trigger payments_direct_write_guard before insert or update or delete on public.payments
for each row execute function public.prevent_order_direct_write();
drop trigger if exists order_adjustments_direct_write_guard on public.order_adjustment_requests;
create trigger order_adjustments_direct_write_guard before insert or update or delete on public.order_adjustment_requests
for each row execute function public.prevent_order_direct_write();
drop trigger if exists order_place_history_direct_write_guard on public.order_place_history;
create trigger order_place_history_direct_write_guard before insert or update or delete on public.order_place_history
for each row execute function public.prevent_order_direct_write();

drop trigger if exists orders_place_scope on public.orders;
create trigger orders_place_scope before insert or update on public.orders
for each row execute function public.assert_order_place_scope();
drop trigger if exists order_items_scope on public.order_items;
create trigger order_items_scope before insert or update on public.order_items
for each row execute function public.assert_order_item_scope();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_combo_components enable row level security;
alter table public.timed_sessions enable row level security;
alter table public.stock_reservations enable row level security;
alter table public.order_place_history enable row level security;
alter table public.order_adjustment_requests enable row level security;
alter table public.payments enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "Orders readable by organization members" on public.orders;
create policy "Orders readable by organization members"
on public.orders for select to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Order items readable by organization admins" on public.order_items;
create policy "Order items readable by organization admins"
on public.order_items for select to authenticated
using (public.is_organization_admin(organization_id));

drop policy if exists "Order combo components readable by organization admins" on public.order_combo_components;
create policy "Order combo components readable by organization admins"
on public.order_combo_components for select to authenticated
using (public.is_organization_admin(organization_id));

drop policy if exists "Timed sessions readable by organization members" on public.timed_sessions;
create policy "Timed sessions readable by organization members"
on public.timed_sessions for select to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Stock reservations readable by organization admins" on public.stock_reservations;
create policy "Stock reservations readable by organization admins"
on public.stock_reservations for select to authenticated
using (public.is_organization_admin(organization_id));

drop policy if exists "Order place history readable by organization admins" on public.order_place_history;
create policy "Order place history readable by organization admins"
on public.order_place_history for select to authenticated
using (public.is_organization_admin(organization_id));

drop policy if exists "Adjustment requests readable by organization members" on public.order_adjustment_requests;
create policy "Adjustment requests readable by organization members"
on public.order_adjustment_requests for select to authenticated
using (public.is_organization_member(organization_id));

drop policy if exists "Payments readable by organization admins" on public.payments;
create policy "Payments readable by organization admins"
on public.payments for select to authenticated
using (public.is_organization_admin(organization_id));

drop policy if exists "Audit logs readable by organization admins" on public.audit_logs;
create policy "Audit logs readable by organization admins"
on public.audit_logs for select to authenticated
using (public.is_organization_admin(organization_id));

grant select on public.employee_workspace_places to authenticated;
grant select on public.employee_orders to authenticated;
grant select on public.employee_order_items to authenticated;
grant select on public.employee_timed_sessions to authenticated;
grant execute on function public.current_user_primary_organization_id() to authenticated;
grant execute on function public.calculate_available_product_stock(uuid) to authenticated;
grant execute on function public.create_order(uuid, text, text) to authenticated;
grant execute on function public.add_product_to_order(uuid, uuid, numeric) to authenticated;
grant execute on function public.add_service_to_order(uuid, uuid, numeric) to authenticated;
grant execute on function public.add_combo_to_order(uuid, uuid, numeric) to authenticated;
grant execute on function public.start_timed_session(uuid, uuid) to authenticated;
grant execute on function public.complete_timed_session(uuid) to authenticated;
grant execute on function public.move_open_order_to_place(uuid, uuid, text) to authenticated;
grant execute on function public.request_order_adjustment(uuid, uuid, public.adjustment_request_type, text, numeric) to authenticated;
grant execute on function public.review_order_adjustment(uuid, text, text) to authenticated;
grant execute on function public.set_order_waiting_payment(uuid) to authenticated;
grant execute on function public.complete_order_payment(uuid, public.payment_method) to authenticated;
grant execute on function public.mark_order_payment_refused(uuid, text) to authenticated;
